import { AlphabetConstructorElem } from './type';


//ԱաԲբԳգԴդԵեԶզԷէԸըԹթԺժԻիԼլԽխԾծԿկՀհՁձՂղՃճՄմՅյՆնՇշՈոՉչՊպՋջՌռՍսՎվՏտՐրՑցՒւՓփՔքԵվևՕօՖֆ
//ԳգԴդԵեԶզԷէԸըԹթԺժԻիԼլԽխԾծԿկՀհՁձՂղՃճՄմՅյՆնՇշՈոՉչՊպՋջՌռՍսՎվՏտՐրՑցՒւՓփՔքԵվևՕօՖֆ
export const armenianAlphabet: AlphabetConstructorElem[] = [
    {upperCase: 'Ա', lowerCase: 'ա', transcription: 'a', letterName: 'ayb'}, 
    {upperCase: 'Բ', lowerCase: 'բ', transcription: 'b', letterName: 'ben'}, 
    {upperCase: 'Գ', lowerCase: 'գ', transcription: 'g', letterName: 'gim'}, 
    {upperCase: 'Դ', lowerCase: 'դ', transcription: 'd', letterName: 'da'}, 
    {upperCase: 'Ե', lowerCase: 'ե', transcription: 'ye', letterName: 'yech'}, 
    {upperCase: 'Զ', lowerCase: 'զ', transcription: 'z', letterName: 'za'}, 
    {upperCase: 'Է', lowerCase: 'է', transcription: 'e', letterName: 'e'}, 
    {upperCase: 'Ը', lowerCase: 'ը', transcription: 'e', letterName: 'yit'}, 
    {upperCase: 'Թ', lowerCase: 'թ', transcription: 'th', letterName: 'tho'}, 
    {upperCase: 'Ժ', lowerCase: 'ժ', transcription: 'zh', letterName: 'zhe'}, 
    {upperCase: 'Ի', lowerCase: 'ի', transcription: 'i', letterName: 'ini'}, 
    {upperCase: 'Լ', lowerCase: 'լ', transcription: 'l', letterName: 'livn'}, 
    {upperCase: 'Խ', lowerCase: 'խ', transcription: 'h', letterName: 'he'}, 
    {upperCase: 'Ծ', lowerCase: 'ծ', transcription: 'cz', letterName: 'cza'}, 
    {upperCase: 'Կ', lowerCase: 'կ', transcription: 'k', letterName: 'ken'}, 
    {upperCase: 'Հ', lowerCase: 'հ', transcription: 'h', letterName: 'ho'}, 
    {upperCase: 'Ձ', lowerCase: 'ձ', transcription: 'dz', letterName: 'dza'}, 
    {upperCase: 'Ղ', lowerCase: 'ղ', transcription: 'y', letterName: 'yat'}, 
    {upperCase: 'Ճ', lowerCase: 'ճ', transcription: 'ch', letterName: 'che'}, 
    {upperCase: 'Մ', lowerCase: 'մ', transcription: 'm', letterName: 'men'}, 
    {upperCase: 'Յ', lowerCase: 'յ', transcription: 'y', letterName: 'yi'}, 
    {upperCase: 'Ն', lowerCase: 'ն', transcription: 'n', letterName: 'nu'}, 
    {upperCase: 'Շ', lowerCase: 'շ', transcription: 'sh', letterName: 'sha'}, 
    {upperCase: 'Ո', lowerCase: 'ո', transcription: 'o', letterName: 'vo'}, 
    {upperCase: 'Չ', lowerCase: 'չ', transcription: 'ch', letterName: 'cha'}, 
    {upperCase: 'Պ', lowerCase: 'պ', transcription: 'p', letterName: 'pe'}, 
    {upperCase: 'Ջ', lowerCase: 'ջ', transcription: 'dzh', letterName: 'dzhe'}, 
    {upperCase: 'Ռ', lowerCase: 'ռ', transcription: 'r', letterName: 'rra'}, 
    {upperCase: 'Ս', lowerCase: 'ս', transcription: 's', letterName: 'se'}, 
    {upperCase: 'Վ', lowerCase: 'վ', transcription: 'v', letterName: 'veu'}, 
    {upperCase: 'Տ', lowerCase: 'տ', transcription: 't', letterName: 'tivn'}, 
    {upperCase: 'Ր', lowerCase: 'ր', transcription: 'r', letterName: 're'}, 
    {upperCase: 'Ց', lowerCase: 'ց', transcription: 'cz', letterName: 'czo'}, 
    {upperCase: 'Ւ', lowerCase: 'ւ', transcription: 'u', letterName: 'u'}, 
    {upperCase: 'Փ', lowerCase: 'փ', transcription: 'p', letterName: 'pivr'}, 
    {upperCase: 'Ք', lowerCase: 'ք', transcription: 'k', letterName: 'ke'}, 
    {upperCase: 'Օ', lowerCase: 'օ', transcription: 'o', letterName: 'o'},
    {upperCase: 'Եվ', lowerCase: 'և', transcription: 'ev', letterName: 'ev'}, 
    {upperCase: 'Ֆ', lowerCase: 'ֆ', transcription: 'f', letterName: 'fe'}, 
]